### ISSUE TITLE
Website documentation

### ISSUE THREAD

**Issue by vitaliihonta** [vitaliihonta/zio-temporal#13]
Add the following pages
- [x] Child workflows
- [x] External workflows
- [x] Continue as new
- [x] Distributed sagas
- [x] Protobuf section
- [x] Testing section

**Comment by carlosedp** [comment]
It would also be nice to have some simpler examples like I've implemented based on Temporal's own Java SDK docs:

- [ ] Simple Temporal worker/client app with one workflow
- [ ] Separate Temporal apps for worker/client and workflow + activity
- [ ] Separate Temporal apps for worker/client and workflow + activity with retry
- [ ] Temporal workflow/activity test

I already have these implemented so once latest refactoring gets merged, I'll update them and send a PR.

**Comment by vitaliihonta** [comment]
For better progress tracking, created a separate #89 ticket
