### ISSUE TITLE
Have separate build files for each example project

### ISSUE THREAD

**Issue by carlosedp** [vitaliihonta/zio-temporal#38]
It would be great to have a build.sbt file for each example instead of using the main one. This way,  people starting with zio-temporal have a clear base on what to use on fresh project.

I can submit this once #36 is merged. Also if desired I can also add the build.sc for Mill (which is the build tool I use as default).

**Comment by vitaliihonta** [comment]
@carlosedp created a new repository for more examples. Feel free to contribute 😄 
https://github.com/vitaliihonta/zio-temporal-samples/tree/main
