### ISSUE TITLE
Testkit improvements

### ISSUE THREAD

**Issue by vitaliihonta** [vitaliihonta/zio-temporal#52]
- [x] Check TestActivityEnvironment example [here](https://github.com/tsurdilo/temporal-java-workshop/blob/main/src/test/java/io/workshop/c1s2/ContentLengthActivityTest.java)

**Comment by alterationx10** [comment]
The issue I've had with is with `TestActivityEnvironment` (which ties to `ZActivity.run`)  is an `ActivityCompletionClient` not being provided (see https://github.com/temporalio/sdk-java/issues/460 ). 

My current workaround was to make a generic WorkFlow that I could inject in the activity method I wanted to run, and wrap it all in the `ZTestWorkflowEnvironment` to execute it for unit testing our activities. I'd be happy to clean up an example some time in the next couple of days, if it would be helpful.

**Comment by muazzam-waheed** [comment]
@vitaliihonta The suggested `TestActivityEnvironment` example falls close to my usecase. Except the example doesn't cover `ActivityCompletionClient` use in implementation class. 

I need a test case, where am testing activity implementation to call an external endpoint in which am using ActivityCompletionClient` with spring webclient. But my workflow implementation in not in same code repo as activity.

**Comment by vitaliihonta** [comment]
cc @alterationx10 
I hope no workarounds are needed for now 😄
