### ISSUE TITLE
Cannot deserialize Either's with JacksonPayloadDataConverter

### ISSUE THREAD

**Issue by vitaliihonta** [vitaliihonta/zio-temporal#69]
**Problem**:
Minimal reproducible example here https://github.com/alterationx10/temporal-either-repro/blob/main/src/test/scala/TemporalEitherSpec.scala.

The problem is that jackson-module-scala needs a type hint for Left/Right value. It worked somehow before untyped-stub rewrite.

**TODO**:
- [x] Try providing a type hint for jackson in TemporalWorkflowFacade
- [x] Examine ZWorkflowStub#result-like methods, so that they also use a type hint

NOTE: izumi reflect may help to do it (it's already available because of zio)

**Comment by alterationx10** [comment]
I pushed some changes to https://github.com/alterationx10/temporal-either-repro

I added projects for zio temporal versions 0.2.0-M6 and 0.1.0-RC6

0.2.0-M6 fails ❌ 
0.1.0-RC6 passes ✅

**Comment by vitaliihonta** [comment]
It should be fixed in `0.2.0-RC2`
